### ISSUE TITLE
Hotkeys are not being unhooked when loading settings

### ISSUE THREAD

**Issue by Toufool** [Toufool/Auto-Split#102]
[avasam-complete branch](https://github.com/Toufool/Auto-Split/tree/avasam-complete)
repro:
- open AutoSplit with no settings
- load a settings file that has a "skip split" hotkey set
- load the same settings file
- when you start AutoSplit, pressing the skip split will make AutoSplit skip two splits instead of just one.
- loading the settings file again and again will cause it to skip split 3 times, 4 times, etc.

**Comment by Avasam** [comment]
That's because they're being cleared out on loadSettings:
```py
def loadSettings(self: AutoSplit, load_settings_on_open: bool = False, load_settings_from_livesplit: bool = False):
    # hotkeys need to be initialized to be passed as thread arguments in hotkeys.py
    self.split_hotkey = ""
    self.reset_hotkey = ""
    self.skip_split_hotkey = ""
    self.undo_split_hotkey = ""
    self.pause_hotkey = ""
```
The initialization should be done in the AutoSplit object itself. I had incidentally fixed this without even knowing it was an issue in my massive linting branch I'm working on (in this commit specifically): https://github.com/Avasam/Auto-Split/commit/9ccf887eb51a2c8a5e3f9eb12263842feb43f71f
