### ISSUE TITLE
2.0.0: Issue Undoing Split during Pause

### ISSUE THREAD

**Issue by Toufool** [Toufool/Auto-Split#181]
repro:
have two split images:
001_SplitImage_[100]
002_SplitImage

When a match occurs for 001_SplitImage_[100], it enters the pause state for 100 seconds. The next split is now 002_SplitImage. 

During that 100 seconds, you should be able to click Undo Split in the "Pause" state and it will go back to 001_SplitImage_[100]. In 2.0.0, clicking Undo Split goes back to that image, but it does not appear.

Same behavior when using `<` button

https://user-images.githubusercontent.com/37423484/198856175-11807f3d-bd9f-4bf0-bd48-57415e650f22.mp4

https://user-images.githubusercontent.com/37423484/198856172-172fd293-e517-4499-9d34-43cf342b1a54.mp4

**Comment by Avasam** [comment]
From Discord:
I believe this was intended. The reasoning: If you have to undo a split with an autosplitter, it's most likely because you hit a false positive. If undoing the split started comparing immediately again, it makes it impossible to go back by more than a single split (as it'll re-trigger immediately)

https://cdn.discordapp.com/attachments/567370622263492623/1041861450077052928/undo_while_paused.mp4

If you prefer the behavior in 1.6.1, then I can make it an option ("Keep comparison paused when undoing split"). Since it's really just about whether or not this check is run

**Comment by Toufool** [comment]
@Avasam I'm super late on this sorry, but yea I think what you described makes sense. We can leave it how it is in 2.0 currently.
