### ISSUE TITLE
2.0.0: Disable `<` and `>` buttons when in a Delayed state

### ISSUE THREAD

**Issue by Toufool** [Toufool/Auto-Split#183]
![image](https://user-images.githubusercontent.com/37423484/198857126-f0b6acee-f453-44be-9242-8b26acb07e6f.png)

We should disable `<` and `>` buttons in the delayed state since they do not do anything.

**Comment by Avasam** [comment]
From Discord:
I believe this was intended. The reasoning: If you have to undo a split with an autosplitter, it's most likely because you hit a false positive. If undoing the split started comparing immediately again, it makes it impossible to go back by more than a single split (as it'll re-trigger immediately)

https://cdn.discordapp.com/attachments/567370622263492623/1041861450077052928/undo_while_paused.mp4

If you prefer the behavior in 1.6.1, then I can make it an option ("Keep comparison paused when undoing split"). Since it's really just about whether or not this check is run

**Comment by Avasam** [comment]
Should be fixed in the next PR.

**Comment by Toufool** [comment]
Confirmed these buttons are now disabled when in the "delayed" state. closing.
