### ISSUE TITLE
Capture card as input

### ISSUE THREAD

**Issue by afresquet** [Toufool/Auto-Split#27]
Sorry if issues are not the place for requests, but I was wondering if it would be possible to get the live capture region directly from a capture card for console games.

It would make for more accurate similarities, wouldn't depend on the size of the game or OBS, and overlays also wouldn't have to require nothing on top of the game.

Also I don't know if this is something I'm doing wrong, but when I try to select a live region on Streamlabs OBS all I get is a black screen but it does work when using OBS Studio, that would also not be a problem with capture card input.

**Comment by Toufool** [comment]
Getting the live capture region directly from the capture card I'm sure is possible but would probably require some sort of video plugin, and then have the program read from that instead of the window region. That would require a ton of work that I probably won't look into.

The streamlabs OBS issue is in [Known Issues](https://github.com/Toufool/Auto-Split#known-issues)

**Comment by afresquet** [comment]
I tried playing around with it myself but sadly only one program can make use of the video input at the same time, so it wouldn't work with the autosplitter and obs at the same time sadly. Tried using an input splitter but the resulting quality was very poor.
