### ISSUE TITLE
Splitting when holding shift

### ISSUE THREAD

**Issue by Sekanor** [Toufool/Auto-Split#30]
I've read that it was a known issue that holding shift, ctrl or alt prevent LiveSplit & WSplit from registering the splitkey correctly.

However, my speedgame implies having to hold shift at some point where a split will occur.

Which is why I'm asking, do you think this issue is likely to get a fix someday? Or is it an issue related to LiveSplit limitations?

If it's actually possible I could help doing so

**Comment by Sekanor** [comment]
Small note - if the split key is something like Insert, the bug does not happen. Might be useful for others than myself

**Comment by Toufool** [comment]
Going to keep this open to remind me to attempt to fix this bug at some point. It definitely needs to be fixed for anyone playing PC games since shift is so common.

**Comment by thquinn** [comment]
Popping in to say that at least one other person wants this feature! (Thanks for a very handy piece of software, by the way.)

**Comment by Avasam** [comment]
@Sekanor & @thquinn 
I'm not sure if I understand this question correctly, but might be fixed by #61 ?
You can try out my latest release https://github.com/Avasam/Auto-Split/releases

**Comment by Avasam** [comment]
Oh I think I understand the issue now. Due to the way it works, I don't think it's likely to be fixed from AutoSplit's side, unless modifiers are supported.
In a way, #60 takes care of that.
However, this seems to have been fixed in LiveSplit anyway, as I can set a key without modifiers, and LiveSplit will still catch it with modifier.

This can be closed in favor of #34
