### ISSUE TITLE
Using the program with different window sizes

### ISSUE THREAD

**Issue by Rocky712YT** [Toufool/Auto-Split#51]
Hello,

I struggled a lot to crop out my region exactly and the problem that results in this, is that it can often come to a slightly different selected region which results into the autosplitter not working accurate.
A way to make the program run in a bigger window or to make the crop tool much bigger to get more precison in cropping the region would be really helpful.

**Comment by kenman345** [comment]
i believe some of the issue will be that using a bigger window means more pixels which going from lets say a 10x10 pixel region to a 15x15 pixel region is more than double the pixels. so the larger the window the more processing power needs to be used. Unless perhaps you can use a bigger window but sample the region at every other pixel so that you're still working internally with a smaller resolution than even before. 

I'll take a look at some of the code and see if something like that is the problem and fixable.

**Comment by Faschz** [comment]
The selected region gets resized along with the given split image to match that of a predetermined size for comparisons. Given how old this issue is, there are some features that have been implemented since v1.

v1.1 
- added the ability to input coordinates for selecting the region allowing you to fine tune the capture
- added additional image comparison methods. Histograms and pHash would be much less effected by the less accurate positioning of the cropped region since they rely on average colors and frequency respectively. L2 Norm was used in v1 and can be heavily influenced by positional changes in high frequency images.

v1.2
- added align image feature, this allows you to crop an overscan of the region and select an image. Autosplit will then try to crop the region so that the best fit matches that of the provided image.
