### ISSUE TITLE
Invalid file name

### ISSUE THREAD

**Issue by Puperger** [Toufool/Auto-Split#62]
![Screenshot 2021-05-05 222149](https://user-images.githubusercontent.com/82495364/117204237-53865180-adf0-11eb-8e94-c009620c0404.png)
I don't know why this happens, can anyone help me?

**Comment by Toufool** [comment]
Hi Puperger,

This error message occurs when you have the "Custom Pause Times" checkbox checked, but there is not a valid custom pause time in ALL of the split image filenames. Either uncheck the "Custom Pause Times", or ensure that each filename has a valid custom pause time. For example, appending `[10]` to that file name so that it includes a custom pause time of 10 seconds: `001_SplitImage_#20000#_[10].png`

**Comment by Avasam** [comment]
There's a feature in #31 and #50 that I'm planning to extract as its own feature/PR which will remove this checkbox and change it for a "default" pause time.
