### ISSUE TITLE
Cross platform?

### ISSUE THREAD

**Issue by DarkJarris** [Toufool/Auto-Split#9]
Will this tool work cross platform? looking at the code it seems to import windows only libraries such as win32gui. 

Seeing as python is cross platform, could instead cross platform libraries be used to allow the tool to run on Linux and Mac too?

**Comment by Toufool** [comment]
AutoSplit has only currently been tested on Windows 7 and Windows 10. It does pull windows binaries, and those binaries are at the core of how the capture region is created and displayed. It would be a significant amount of work for this to be reworked for Linux and Mac because of this. For right now, we do not plan to support Linux and Mac.
